"""
Django settings for itworkout project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f0+tr@c8n=)z97x=#!gl)*yx)c(27$dwq)j-szv8aig7@1s#tq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["54.165.80.189"]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'workout',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'itworkout.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'itworkout.wsgi.application'

ASGI_APPLICATION = 'itworkout.asgi.application'
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "itworkout",
        "USER": "postgres",
        "PASSWORD": "password",
        "HOST": "database-1.cbtjmytkqigs.us-east-1.rds.amazonaws.com",
        "PORT": "5432",
      }
  }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

AWS_ACCESS_KEY_ID = 'ASIA3G647IU3IVJQMQWH'
AWS_SECRET_ACCESS_KEY = '/9c4L640fXIvScwSGmZ2mgm90CmoRskuG40LWbUk'
AWS_SESSION_TOKEN = 'IQoJb3JpZ2luX2VjEEoaCXVzLXdlc3QtMiJHMEUCIBQrbrcfoYccbmDXS2ZIJ8NSm/OUAOWmnrIUSka8kyFEAiEA3Y8bSOhI1SUSJH6bKZzEZ93n98EFT5jANBVl+2SbuIQqrgIIExAAGgw3NzA4NzMxODE0OTQiDNEvx1RyJWsRblM51yqLAtZYhyrAI8a94rZGqh+tcxSedDxmZ/RF2+zf/mmr5j/wCwgEGzouuQjvtyEmoNHND38r7qx4DZG9GhhxZ6KUAOsP1tIQdjmlJSgheg+qvDC5D1Oz/P4dRNXs3v5XHCQ2k0YITA6D7GFxUvkkvR9v0RLAd1xx1fXrQXxwuOZ5GtcYpn6RrMKDtP0tJQQBViwHXy/fXeuXvXw67pa+VeMNqsTqCNLRUwGBqGvRrumCzF+FVwrYUVc0pN3zBSy5ofG6EQswRrzNWbhgsMICCT1QNLGLF37VwO6w2Q37RaMw8FPOuR6T8pKL67QKVXJ+Af2HGK583RsQI2yXCOzOkzDeYSCjIYzGPnqWZeDO1zDemJLIBjqdAbyUOEeOA1SJSHOLKvrLVT9Jtmls7PGDAfByxZSfI81PHDL7VOiTozqPfMcV/yvnFa7E4Nws1GCd9gfcTxVF4neiwjsLY+L/dcWFtxIxD+LLN6hSpT/zjqHZuF84xKXL98MSuC6nsL9607GRyz5i/PnHYP0Bkq7xZQTYRr8AJ0z0OpjeChO2mtZn83TPvJCVpxXHREXzDFATxsOZ798='
AWS_STORAGE_BUCKET_NAME = 'itworkout'
AWS_S3_REGION_NAME = 'us-east-1'



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

TIME_INPUT_FORMATS = (
    '%H:%M:%S',  # e.g., '14:30:59'
    '%H:%M',     # e.g., '14:30'
)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'

# บอกให้ S3 storage ใช้ prefix 'image'
AWS_LOCATION = 'image'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# แล้วตั้ง MEDIA_URL ให้สอดคล้องกับ AWS_LOCATION
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'image')
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'public-read'  # หรือ 'private' แล้วแต่ต้องการ
AWS_QUERYSTRING_AUTH = False




LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'trainers'

# Channels channel layer: in-memory backend for development.
# For production use Redis: channels_redis.core.RedisChannelLayer
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

